_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 16
bn_momentum:
    value: <utils.utils.PN2_BNMomentum object at 0x755494c47370>
dropout:
    value: 0.5
epoch:
    value: 200
estimate:
    value: true
gpu:
    value: "1"
model:
    value:
        type: openad_pn2
        weights_init: pn2_init
partial:
    value: false
rotate:
    value: None
rotate_type:
    value: null
seed:
    value: 1
semi:
    value: false
train_affordance:
    value:
        - grasp
        - contain
        - lift
        - openable
        - layable
        - sittable
        - support
        - wrap_grasp
        - pourable
        - move
        - displaY
        - pushable
        - pull
        - listen
        - wear
        - press
        - cut
        - stab
        - none
val_affordance:
    value:
        - grasp
        - contain
        - lift
        - openable
        - layable
        - sittable
        - support
        - wrap_grasp
        - pourable
        - move
        - displaY
        - pushable
        - pull
        - listen
        - wear
        - press
        - cut
        - stab
        - none
workflow:
    value:
        train: 1
        val: 1
zero_affordance:
    value:
        - grab
        - accommodate
        - raise
        - unlock
        - rest
        - take a seat
        - bear
        - wrap
        - pour
        - reposition
        - demonstrate
        - push
        - drag
        - hear
        - clothe
        - thumb
        - slice
        - jab
        - none
